- extension_service/app/app_test.py
- extension_service/datastore/datastore.py
- extension_service/datastore/providers/postgres.py
Flight search app_test is not yet fully tested (flight num and airlines are not tested yet). Just update the function to use parametrize testing. 
Keep endpoint functions consistent (airport and amenities are getting updated in another PR):
Remove Optional from flight search function since it is returning empty list.
Update flight get function to use fetchrow and return None when nothing is returned.
> chore: parametrize flights search app_test and update search return

- extension_service/app/app_test.py
- extension_service/app/routes.py
- extension_service/datastore/datastore.py
- extension_service/datastore/providers/postgres.py
- extension_service/datastore/providers/postgres_test.py
Refactor get airport endpoint to include iata as param. 
Add search airports endpoint with city and/or country and/or name as param.
Did not add unit test for the providers now, will work on tests when add integration test in future PR.
> chore: refactor get airport endpoint and add search airport endpoint

- .github/trusted-contribution.yml
Adds comment `/gcbrun` to renovate bot PRs in order to trigger tests
> ci: add trusted contribution bot

- docs/datastore/alloydb.md
extra space was breaking copy/paste
> fix: update alloydb.md to remove extra trailing space

- docs/datastore/alloydb.md
previous URL didn't work for git clone operation (permission denied)
> Update alloydb.md fix git clone URL

- docs/deploy_extension_service.md
Correct API name is: run.googleapis.com (not "cloudrun.googleapis.com")
> Update deploy_extension_service.md fix typo in cloud run service

- .github/renovate.json
Update aynscpg and asyncpg-stubs together to fix the conflicting dependency error raised by renovate update.
> chore: group aynscpg and asyncpg-stubs for renovate updates

- .github/renovate.json
Renovate rebases on every merge into main. To reduce the churn on multiple dependency updates, we can manually rebase/update the branch.
> chore: turn off renovate rebase

- docs/deploy_extension_service.md
Currently the VPC network flags `--network` and `--subnet` are only available on the gcloud alpha track according to: https://cloud.google.com/sdk/gcloud/reference/alpha/run/deploy and https://cloud.google.com/sdk/gcloud/reference/run/deploy.
Update cloud run deployment instruction to reflect this.
> feat(docs): update gcloud track for deployment with VPC network 

- extension_service/datastore/providers/firestore.py
Noticed a bug in the Firestore provider while taking this on a test run - many of the methods with the Firestore provider do not add the ID to the document and therefore fail model validation. Additionally, some places had incorrect conversion of documents into dict (using `dict(doc)` instead of `doc.to_dict()`). This PR resolves both of these issues.
> fix(firestore): Add ID to all documents in Firestore provider

- docs/datastore/alloydb.md
Update command to always get the latest ubuntu-2004-focal disk.
Tested the updated command.
> chores: update gce create command

- retrieval_service/alloydb.tests.cloudbuild.yaml
Since it's not stored in Google (like in Cloud Storage or another service), it will be cleaned up automatically after the test run.
> chores: remove file cleanup step

- retrieval_service/datastore/providers/cloudsql_postgres.py
- retrieval_service/datastore/providers/firestore.py
- retrieval_service/datastore/providers/postgres.py
when convert date into timestamp in postgresql, it will assign a default time of 00:00:00. Hence, our search return includes flights that are on the previous day.
fix by fixing the departure_time filtering sql statement.
> chores: update search flight sql

- langchain_tools_demo/tools.py
When user query about a specific flight (agent return "the flight is UA xxx departing at xx/xx/xx"), and then asked a follow-up question (e.g. What is the departure gate?), the agent returned a flight using the get_flight tool with the wrong parameter (flight_number as id).
The langchain memory only includes previous conversation (and not query results), hence, it will not have access to the id if it is not mentioned in past conversation. In the above example, the agent mistaken flight number as id.
Removing get_flight endpoints seems to help with this. Manually tested and seems to help by limiting the number of tools for the agent. Currently, there are no foreseeable scenario when the agent will use get endpoints (with id), hence decided to remove get endpoints for all the dataset …
> chores: remove get endpoints

- langchain_tools_demo/static/index.js
- langchain_tools_demo/templates/index.html
Adjusts the LangChain Tools Demo to use relative paths so that it still works for TLs that run overly complicated IDE setups that need a proxy to access everything.
> fix(langchain_tools_demo): use relative paths for resources

- llm_demo/static/index.css
- llm_demo/templates/index.html
Move the reset button to not be behind
the Google Login Banner
> chore: fix the refresh icon hiding behind Google banner

- llm_demo/orchestrator/langchain_tools/tools.py
Made clarifying questions more clear to LLM (hopefully).
Added comments explaining why so many examples are statically coded into the tool descriptions.
Fixed a few minor typos.
> Better clarifying question prompt

- docs/datastore/alloydb.md
- docs/datastore/postgres.md
- retrieval_service/alloydb.tests.cloudbuild.yaml
- retrieval_service/spanner.tests.cloudbuild.yaml
AlloyDB public IP database need to be created by creating a private alloydb instance first. Added VPC-peerings steps.
And a quick fix on spanner ci/cd (removing unnecessary secret env).
> docs: add vpc peering instructions to alloydb instructions

- llm_demo/templates/index.html
Fixes an issue with the llm_demo app template.
loginUri was adding 'login/google' to the whole URL, including query params.
This fix strips query parameters before concatenating 'login/google'.
> fix: strip query params in loginUri

- retrieval_service/datastore/providers/alloydb.py
- retrieval_service/datastore/providers/cloudsql_mysql.py
- retrieval_service/datastore/providers/cloudsql_postgres.py
- retrieval_service/requirements.txt
The Cloud SQL Python Connector just released a new version `v1.10.0`,
same with AlloyDB Python Connector `v1.2.0` that support setting the
`refresh_strategy` argument of the connector.
Setting the refresh strategy to lazy refresh is recommended for
serverless environments. As the default refresh strategy is to
have background refreshes occur to get the instance metadata and a fresh
certificate to use for the SSL/TLS connection.
However, these background refreshes can be throttled when serverless
environments scale to zero (Cloud Functions, Cloud Run etc.).
This PR will fix the ambiguous errors that are a result of the CPU being
throttled for connectors.
> fix: use lazy refresh for AlloyDB and Cloud SQL Connector

- llm_demo/evaluation/eval_golden.py
Adding golden datasets that will be used in llm system evaluation.
The golden dataset is separated into multiple types of queries:
- queries that uses a specific tool
- airline related queries (no tool calling - answer is within prompt)
- assistant related question (no tool calling - answer is within prompt)
- out of context questions (no tool calling)
- multitool selections (agent selecting multiple tool before returning a final answer to the user)
> chore: add golden dataset for eval

- llm_demo/evaluation/__init__.py
- llm_demo/evaluation/eval_golden.py
- llm_demo/evaluation/evaluation.py
Add the function to get prediction for each of the queries from golden_dataset. Prediction is used as comparison to retrieve metrics.
Usage example:
```
from evaluation import run_llm_for_eval, goldens
eval_list = await run_llm_for_eval(goldens, orchestration, session, session_id)
```
> chore: get prediction for eval dataset

- llm_demo/evaluation/__init__.py
- llm_demo/evaluation/eval_golden.py
- llm_demo/evaluation/evaluation.py
- llm_demo/requirements.txt
Add the function to run evaluation for retrieval phase (evaluating the llm ability to pick and utilize tools that are given).
Usage example:
```
eval_results = evaluate_retrieval_phase(eval_datas)
```
> chore: add retrieval phase evaluation

- llm_demo/evaluation.cloudbuild.yaml
- llm_demo/evaluation/evaluation.py
- llm_demo/requirements.txt
- llm_demo/run_evaluation.py
Add run_evaluation.py file and automatic cloudbuild trigger during PR.
Cloudbuild trigger will automatically run the evaluation and the results will be added to GCP under vertexai/experiments.
Detailed metric table (with row specific metrics) could be obtain by running locally with `export EXPORT_CSV=True`.
> chore: add cloudbuild and run_evaluation file

- llm_demo/orchestrator/langgraph/langgraph_orchestrator.py
- llm_demo/orchestrator/langgraph/react_graph.py
- llm_demo/orchestrator/langgraph/tool_node.py
- llm_demo/orchestrator/langgraph/tools.py
- llm_demo/requirements.txt
Update implementation to langgraph.
Main changes:
- We create a `UserAgent` for each session in langchain orchestration. For langgraph, we create a single graph and use `config` with `thread_id` to keep track of session. 
This PR does not include the following:
- human-in-the-loop workflow (e.g. book ticket confirmation from user).
- initialize tools with user-specific client. Currently the tools is initialized with a single client (each session/user is supposed to have their own client). Will create a custom ToolNode in another PR so that the Tool is able to get user's `client` object from the state.
> chore: implement langgraph

- retrieval_service/datastore/providers/neo4j_graph.py
- retrieval_service/datastore/providers/neo4j_graph_test.py
Add `category` label nodes to the current graph, and connect already existing `amenities` label nodes to them through `BELONGS_TO` relationship. 
Add test cases to:
- Guarantee the successful creation of `category` nodes based on the categories found on the current `amenity_dataset.csv` 
- Guarantee the successful creation of `BELONGS_TO` relationships, one per amenity node based on their category field on the current `amenity_dataset.csv`
> feat: Add category label nodes and BELONGS_TO relationships

- data/relationships/amenity_relationships.csv
- retrieval_service/datastore/providers/neo4j_graph.py
- retrieval_service/datastore/providers/neo4j_graph_test.py
Add `SIMILAR_TO` relationship to the current amenity knowledge graph through csv file ingestion.
File has a format of source id from one node (src_id) , relationship type (rel_type) and target id to the other node (tgt_id).
Which then will be ingested by the `create_relationships` function to be processed as a Cypher query.
> feat: Add similar_to relationship from csv ingestion

- llm_demo/evaluation.cloudbuild.yaml
- llm_demo/evaluation/__init__.py
- llm_demo/evaluation/eval_golden.py
- llm_demo/evaluation/evaluation.py
- llm_demo/requirements.txt
- llm_demo/run_evaluation.py
- retrieval_service/app/routes.py
Implementation of llm system evaluation. 
Usage example: 
If would like to output detailed metric table (row-specific scores), add the following env var `export EXPORT_CSV=True`
Run the following: `python run_evaluation.py`
> feat: Implement llm system evaluation

- retrieval_service/datastore/datastore.py
- retrieval_service/datastore/providers/alloydb.py
- retrieval_service/datastore/providers/cloudsql_mysql.py
- retrieval_service/datastore/providers/cloudsql_mysql_test.py
- retrieval_service/datastore/providers/cloudsql_postgres.py
- retrieval_service/datastore/providers/cloudsql_postgres_test.py
- retrieval_service/datastore/providers/firestore.py
- retrieval_service/datastore/providers/neo4j_graph.py
- retrieval_service/datastore/providers/postgres.py
- retrieval_service/datastore/providers/spanner_gsql.py
Exposing user ID and email to LLM is unnecessary and we should remove them from `list_tickets()` results for increased security.
1. Modify queries to return only necessary columns.
2. Remove `Ticket` model validation when returning results from tickets endpoints.
> feat: Remove user ID and user email from `list_tickets()` result

- retrieval_service/app/app_test.py
- retrieval_service/app/routes.py
- retrieval_service/datastore/datastore.py
- retrieval_service/datastore/providers/alloydb.py
- retrieval_service/datastore/providers/alloydb_test.py
- retrieval_service/datastore/providers/cloudsql_mysql.py
- retrieval_service/datastore/providers/cloudsql_mysql_test.py
- retrieval_service/datastore/providers/cloudsql_postgres.py
- retrieval_service/datastore/providers/cloudsql_postgres_test.py
- retrieval_service/datastore/providers/firestore.py
- retrieval_service/datastore/providers/neo4j_graph.py
- retrieval_service/datastore/providers/neo4j_graph_test.py
- retrieval_service/datastore/providers/postgres.py
- retrieval_service/datastore/providers/postgres_test.py
- retrieval_service/datastore/providers/spanner_gsql.py
- retrieval_service/datastore/providers/spanner_gsql_test.py
retrieval service to return results and sql query. Sql query will be used to display tracing at the frontend.
This PR only add sql return for postgres and alloydb provider. Other providers will be added in a separate PR.
> chore: add sql return to retrieval service

- retrieval_service/datastore/providers/alloydb_test.py
- retrieval_service/datastore/providers/cloudsql_mysql_test.py
- retrieval_service/datastore/providers/cloudsql_postgres_test.py
- retrieval_service/datastore/providers/spanner_gsql_test.py
Fix post-yield code not running during teardown.
Update async fixtures to @pytest_asyncio.
> fix: update pytest to pytest_asyncio for async fixtures

- retrieval_service/datastore/providers/alloydb.py
- retrieval_service/datastore/providers/cloudsql_postgres.py
- retrieval_service/datastore/providers/cloudsql_postgres_test.py
- retrieval_service/datastore/providers/postgres_datastore.py
Create a common `PostgresDatastore` class to encapsulate all the DB query logic based on a given connection pool. Reuse the same logic across AlloyDB & CloudSQL Postgres providers for better code maintainability and less redundancy.
> feat: Consolidate postgres providers

- docs/datastore/cloudsql_mysql.md
Updated integration with this:
https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/pull/104
but have not yet updated the sample app.
> docs(source/cloudsql_mysql): update cloudsql_mysql.md to indicate supported maintenance versions

- llm_demo/orchestrator/orchestrator.py
Updates model name since `gemini-pro` seems deprecated now.
> chore: update model

- tools.yml
This PR adds a tools file equivalent to all the tools in the Cymbal Air app.
> [!NOTE]
> This tools file makes use of the new optional params feature (`default: ""`) from [#617](https://github.com/googleapis/genai-toolbox/pull/617).
> feat: Add tools file for the Cymbal Air tools
