docs/deploy_extension_service.md

adding correct service name and explicitly specifying the region

Update deploy_extension_service.md fixing proxy run command

---

docs/datastore/alloydb.md

Clearly tell the user to update the host and password fields.

Update alloydb.md make config.yml changes more clear

---

.github/labels.yml
.github/trusted-contribution.yml

Add support for dependabot updates (example https://github.com/GoogleCloudPlatform/database-query-extension/pull/49)

chore: Update trusted-contribution.yml

---

docs/datastore/alloydb.md
docs/deploy_extension_service.md

After Megan's friction log: https://b.corp.google.com/issues/310027201

chore: update cloudrun deployment instruction

---

extension_service/datastore/providers/postgres.py

Update syntax for flight search to ILIKE (case insensitive).
Rearrange initialize_data function to have same sequence (airports -> amenities -> flights).
Remove duplicate connection creation in initialize_data function.

chores: update syntax and rearrange import sequence

---

docs/datastore/firestore.md

Add Firestore setup instruction & fix alloydb instruction error

feat(doc): Add Firestore setup instruction

---

docs/datastore/alloydb.md
docs/deploy_retrieval_service.md
docs/run_langchain_demo.md

Found some inconsistency/bugs during testing.

chores: update instructions 

---

README.md

Fixed the LangChain and Retrieval service app links.

Fixed broken links to demo apps

---

retrieval_service/alloydb.tests.cloudbuild.yaml
retrieval_service/datastore/providers/cloudsql_postgres_test.py
retrieval_service/datastore/providers/postgres_test.py
retrieval_service/pyproject.toml

also update alloydb ci/cd workflow to ignore cloudsql integration test.
This PR does not include adding cloud sql CI/CD cloudbuild workflow. Will add it in a separate PR.

feat: add cloudsql integration test

---

langchain_tools_demo/agent.py
langchain_tools_demo/main.py
langchain_tools_demo/static/index.css
langchain_tools_demo/static/index.js
langchain_tools_demo/templates/index.html
langchain_tools_demo/tools.py

This fixes two edge cases:
1. Where the user has a session uuid, but there is no agent associated with it (e.g. instance shut down/restarted)
2. When an agent is reinitialized (such as reset) it preserves the existing memory in the agent's memory

fix(langchain_tools_demo): fix agent concurrency between restarts

---

docs/run_langchain_demo.md
langchain_tools_demo/tools.py

Fixes: https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/issues/190

fix: Add ID Token credential flow for GCE

---

retrieval_service/app/app.py
retrieval_service/app/routes.py
retrieval_service/example-config.yml

fix issue: https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/issues/206

fix: Make `clientId `optional in config.yml

---

llm_demo/templates/index.html

Fix merge conflict with Andy's title change.

chore: Fix Bug with App Header

---

llm_demo/static/index.css
llm_demo/templates/index.html

feat: minor UI improvements

---

llm_demo/static/index.css
llm_demo/static/index.js
llm_demo/templates/index.html

Minor UI Updates
- Spinning loader
- Change to nav bar

feat: minor UI updates

---

llm_demo/app.py
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langchain_tools/tools.py
llm_demo/orchestrator/orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/functions.py
llm_demo/static/index.css
llm_demo/static/index.js
llm_demo/templates/index.html

Ticket confirmation functionality allows you to confirm or decline a ticket booking before the tool finalized the change

feat: Ticket confirmation functionality

---

retrieval_service/app/app.py
retrieval_service/app/routes.py
retrieval_service/requirements.txt
retrieval_service/run_generate_embeddings.py

Update deprecated embeddings library for langchain.

chore: update langchain library for embeddings

---

llm_demo/static/index.css
llm_demo/static/index.js
llm_demo/templates/index.html

https://screencast.googleplex.com/cast/NDU2OTAxMzU0MjcxNTM5Mnw4MjhhYzhlMi1jMA

feat: increase font-size and make UI better

---

llm_demo/requirements.txt
retrieval_service/requirements.txt

cloud-bigquery pull by google-cloud-aiplatform pulled by langchain-google-vertexai

chore: fix deps for bq

---

llm_demo/app.py
llm_demo/orchestrator/langchain_tools/helpers/__init__.py
llm_demo/orchestrator/langchain_tools/helpers/tool_trace.py
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langchain_tools/tools.py
llm_demo/static/index.css
llm_demo/static/index.js
retrieval_service/app/app_test.py
retrieval_service/app/routes.py
retrieval_service/datastore/datastore.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/cloudsql_postgres_test.py
retrieval_service/datastore/providers/firestore.py
retrieval_service/datastore/providers/postgres.py
retrieval_service/datastore/providers/postgres_test.py
retrieval_service/helpers/__init__.py
retrieval_service/helpers/helpers.py

Add Tracing from Retrieval service and NL2Query service.
https://screencast.googleplex.com/cast/NTc5NzM4MTgwNjIyNzQ1NnxlMDNlODMwNy01Yg

Add Tracing

---

llm_demo/static/index.css
llm_demo/static/index.js
retrieval_service/datastore/providers/postgres.py
retrieval_service/helpers/helpers.py
retrieval_service/pyproject.toml
retrieval_service/requirements.txt

https://screencast.googleplex.com/cast/NDgzNDQyMzAyNjQ4MzIwMHwzZjkzYWJlMi1lNw

feat: Tracer formatting updates

---

llm_demo/orchestrator/langchain_tools/tools.py

Additional examples for policy search and NL search.  Reworded examples to pass relative date info to NL2Query.  Provided some more specific examples.

Update tools.py with additional examples

---

llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langchain_tools/tools.py
retrieval_service/app/routes.py
retrieval_service/datastore/datastore.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/firestore.py
retrieval_service/datastore/providers/postgres.py
retrieval_service/helpers/helpers.py

Check flight info and validate seat before booking

Check flight info and validate seat before booking

---

llm_demo/orchestrator/langchain_tools/helpers/tool_trace.py
llm_demo/orchestrator/langchain_tools/tools.py

Allow time as input to departure_time to detect issues

Fix time for demo

---

llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py

Add non deterministic retry logic to langchain
errors on formatting or context window limitations up to 3 retries
pass back errors on later retries to help mitigate issues.

langchain retries

---

llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py

Existing vertex ai orchestrator uses chat model instead of text model. This PR updates the vertex AI orchestration to use text model instead.

chore: update function calling to use llm model

---

docs/datastore/spanner.md

Adding docs for spanner datastore

docs: Adding docs for spanner datastore

---

README.md

Fix typo in README, `managers` -> `manage`

chore: Update typo in README.md

---

.github/sync-repo-settings.yaml
DEVELOPER.md
README.md
docs/datastore/alloydb.md
docs/datastore/cloudsql_postgres.md
docs/datastore/firestore.md
docs/datastore/postgres.md
docs/deploy_retrieval_service.md
docs/run_llm_demo.md
retrieval_service/datastore/__init__.py
retrieval_service/datastore/providers/__init__.py
retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/alloydb_test.py
retrieval_service/datastore/providers/postgres_test.py
retrieval_service/example-config-alloydb.yml
retrieval_service/postgres.tests.cloudbuild.yaml
retrieval_service/requirements.txt

Add alloydb provider utilizing alloydb-python-connector.
Add connector library to requirement.txt.

Add alloydb provider

---

llm_demo/orchestrator/langchain_tools/tools.py
retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/firestore.py
retrieval_service/datastore/providers/postgres.py
retrieval_service/datastore/providers/spanner_gsql.py

Agent sometimes confused the string return from tool as final answer.
Update tool return to be json instead of string.

chore: update tool return

---

.github/renovate.json

fix: update renovate config

---

.github/renovate.json
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py
llm_demo/requirements.txt
retrieval_service/requirements.txt

Also added langchain_community since ChatHistoryMessage is moved to that library.

chore: update langchain renovate group

---

llm_demo/app.py
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langchain_tools/tools.py
llm_demo/orchestrator/orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py
retrieval_service/app/app_test.py
retrieval_service/app/routes.py
retrieval_service/datastore/datastore.py
retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/alloydb_test.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/cloudsql_postgres_test.py
retrieval_service/datastore/providers/spanner_gsql.py
retrieval_service/models/models.py
retrieval_service/run_database_export.py
retrieval_service/run_database_init.py
retrieval_service/run_generate_policy_dataset.py

There are a ton of unused imports in this repo, along with other flake8 issues. This PR cleans up a number of them.

chore: cleanup unused imports

---

llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langchain_tools/tools.py
retrieval_service/app/app_test.py
retrieval_service/app/routes.py
retrieval_service/coverage/.app-coveragerc
retrieval_service/coverage/.cloudsql-coveragerc
retrieval_service/datastore/datastore.py
retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/firestore.py
retrieval_service/datastore/providers/postgres.py
retrieval_service/datastore/providers/spanner_gsql.py

Existing booking ticket require the right information for all the fields. Agent retrieve information from chat history, hence, sometimes it will hallucinate information if it is not recorded in the chat history.
**Existing booking workflow:**
user request to book flight -> present confirmation page (sometimes with hallucinated information) -> book ticket (will fail if information inaccurate) -> ticket booked confirmation or failure
**New booking workflow:**
user request to book flight -> validate ticket (using airline, flight number, departure airport, departure time) -> retrieve other information from flight (such as arrival airport, arrival time etc.) -> present confirmation page to user (with accurate information) -> book ticket -> ticket booked confirmation

feat: add confirmation for ticket booking

---

version.txt

chore: release 0.1.0

---

DEVELOPER.md
README.md
docs/clean_up.md
docs/deploy_retrieval_service.md

Update docs to include MySQL as a datastore provier

docs: Update README.md to list Cloud SQL MySQL as a database

---

llm_demo/orchestrator/langgraph/__init__.py
llm_demo/orchestrator/langgraph/langgraph_orchestrator.py
llm_demo/orchestrator/langgraph/tools.py

Duplicate the langchain orchestration folder to langgraph. Next PR will make changes for the implementation for LangGraph.

chore: duplicate langchain to langgraph

---

retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/cloudsql_postgres_test.py

Also updated alloydb's sqlalchemy syntax for ticket insertion.

feat: add ticket validation and insertion to cloudsql postgres

---

llm_demo/evaluation/eval_golden.py
llm_demo/evaluation/evaluation.py

Update evaluation goldens to use dynamic dates when evaluating query that uses term like "today" or "tomorrow".

chore: update dataset to use dynamic dates

---

llm_demo/evaluation.cloudbuild.yaml
llm_demo/evaluation/eval_golden.py
llm_demo/evaluation/evaluation.py
llm_demo/run_evaluation.py

Update name to differentiate experiment on GCP portal.

chore: update experiment name

---

llm_demo/app.py
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langgraph/langgraph_orchestrator.py
llm_demo/orchestrator/langgraph/react_graph.py
llm_demo/orchestrator/langgraph/tool_node.py
llm_demo/orchestrator/langgraph/tools.py
llm_demo/orchestrator/orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py

This PR add a new edge and nodes for flight booking workflow. This workflow include requiring human confirmation for flight booking.
Existing:
user ask to book flight -> agent -> insert ticket tool (often times agent might be providing inaccurate information about a flight)
Update:
user ask to book flight -> agent -> validate flight (validate if flight exist and retrieve all the accurate information) -> ask for user confirmation with the flight information -> insert ticket tool

chore: add flight booking workflow

---

.github/sync-repo-settings.yaml
llm_demo/langgraph.int.tests.cloudbuild.yaml

Add cloudbuild integration for langgraph.

ci: add langgraph integration

---

.github/sync-repo-settings.yaml
llm_demo/app.py
llm_demo/langgraph.int.tests.cloudbuild.yaml
llm_demo/orchestrator/langchain_tools/langchain_tools_orchestrator.py
llm_demo/orchestrator/langgraph/__init__.py
llm_demo/orchestrator/langgraph/langgraph_orchestrator.py
llm_demo/orchestrator/langgraph/react_graph.py
llm_demo/orchestrator/langgraph/tool_node.py
llm_demo/orchestrator/langgraph/tools.py
llm_demo/orchestrator/orchestrator.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py
llm_demo/requirements.txt

Langgraph is introduced in langchain v0.2.0. The legacy langchain agent (implemented in the `langchain-tools` orchestration) is deprecated in langchain v0.2.0 and will soon be removed in the newer version of langchain.
This PR adds a new orchestration - langgraph

feat: Add langgraph orchestration

---

DEVELOPER.md

docs: add docs for evaluation

---

llm_demo/orchestrator/langchain_tools/tools.py
llm_demo/orchestrator/langgraph/tools.py
llm_demo/orchestrator/vertexai_function_calling/function_calling_orchestrator.py
llm_demo/static/trace.js
retrieval_service/app/routes.py

No-op change. Only updating the return from tools and remove error from tracing.

chore: update return from tools for langchain and function calling

---

DEVELOPER.md
README.md

Add link to Neo4j database setup to README.md file

docs: Update README.md with Neo4j link to config

---

llm_demo/app.py
llm_demo/orchestrator/langgraph/langgraph_orchestrator.py
llm_demo/orchestrator/langgraph/tool_node.py
llm_demo/orchestrator/langgraph/tools.py
llm_demo/static/index.css
llm_demo/static/index.js
llm_demo/static/trace.js
llm_demo/templates/index.html
retrieval_service/app/app_test.py
retrieval_service/app/routes.py
retrieval_service/datastore/datastore.py
retrieval_service/datastore/helpers.py
retrieval_service/datastore/providers/alloydb.py
retrieval_service/datastore/providers/alloydb_test.py
retrieval_service/datastore/providers/cloudsql_mysql.py
retrieval_service/datastore/providers/cloudsql_mysql_test.py
retrieval_service/datastore/providers/cloudsql_postgres.py
retrieval_service/datastore/providers/cloudsql_postgres_test.py
retrieval_service/datastore/providers/firestore.py
retrieval_service/datastore/providers/neo4j_graph.py
retrieval_service/datastore/providers/neo4j_graph_test.py
retrieval_service/datastore/providers/postgres.py
retrieval_service/datastore/providers/postgres_test.py
retrieval_service/datastore/providers/spanner_gsql.py
retrieval_service/datastore/providers/spanner_gsql_test.py
retrieval_service/pyproject.toml
retrieval_service/requirements.txt

Tracing is only implemented in langgraph orchestration and postgres provider.

feat: Add tracing to langgraph orchestration and postgres provider

---

llm_demo/evaluation/eval_golden.py
llm_demo/orchestrator/langchain_tools/tools.py
llm_demo/orchestrator/langgraph/tools.py
retrieval_service/datastore/providers/alloydb_test.py
retrieval_service/datastore/providers/cloudsql_mysql_test.py
retrieval_service/datastore/providers/cloudsql_postgres_test.py
retrieval_service/datastore/providers/postgres_test.py
retrieval_service/datastore/providers/spanner_gsql_test.py
retrieval_service/datastore/providers/spanner_postgres_test.py

feat!: updated flights dataset to 2025

---

docs/datastore/cloudsql_mysql.md
retrieval_service/datastore/providers/cloudsql_mysql.py
retrieval_service/datastore/providers/cloudsql_mysql_test.py

Removed vector index usage due to 1k embedding minimum. Also updated search syntax

chore(cloudsql-mysql)!: Update app to use GA MySQL syntax
